### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mehcode** [mehcode/shio-rs#1]
Moved to separate issues:
 - #14
 - #13
 - #12 
 - #11 
 - #10

**Comment by saggit** [comment]
for common scenarios may be `cookie` and `session` as well?

**Comment by rrichardson** [comment]
For file upload I might recommend https://github.com/abonander/multipart-async

**Comment by mehcode** [comment]
@saggit Added to the list of examples we should make.

---

@rrichardson I'll keep that in mind. If you feel up to it, a rough example of using it would help ( like [json](https://github.com/mehcode/salt-rs/blob/master/examples/json.rs) ), then we can work on moving what needs to be moved to make it ergonomic.

**Comment by abonander** [comment]
My gratitude to @rrichardson for the pre-release plug but I'm just reaching a point where I think I can be happy with the API, though I'm still mulling over a possible architectural shift. 

With the current design, the entry point is [`server::Multipart`](https://github.com/abonander/multipart-async/blob/master/src/server/mod.rs#L71), which mostly just wraps the internal state machine. Then the meat is in [`Multipart::poll_field()`](https://github.com/abonander/multipart-async/blob/master/src/server/mod.rs#L90), which either returns the current field being read, or starts on the next field in the request. A `Field` provides the field headers (name, content type, filename) as well as a `Stream` which yields byte buffers for the field's data only.

To me, this is a compromise between a potential composability hazard, not just being a stream of streams and thus missing out on all the different combinators available, and the additional refcounting and internal bookkeeping needed to make this work as a stream of streams, since each `Field` refers back to the same parent stream and needs to know not to pull chunks before the previous field is finished being read. By being borrow-based, some of the overhead can be avoided at compile-time but it takes a bit of boilerplate to fit into the future/stream paradigm.

As a convenience I provide [`Multipart::fold_fields()`](https://github.com/abonander/multipart-async/blob/master/src/server/mod.rs#L112) which wraps most of this stuff and gives a `Future` which can be polled for the folded state. This seems a little more difficult to work with than an equivalent `Stream` implementation, especially given that the closure will be invoked more than once for more than one field. At least with `Stream::fold()`, it's expected to return a `Future` to resolve the item, which would also be useful here.

So I'm thinking that I want to rearchitect `Multipart` to become a `Stream` of `Field`s, but the main issue is that it would need to be refcounted+internally mutable and have some measure of bookkeeping to avoid fields reading each others' data. I don't think the overhead would be too terrible, especially considering that it wouldn't be cloning and dropping nearly as much. Refcounting+internal mutation seems to be a common tool in futures-based code anyway.

**Comment by Meralis40** [comment]
For the `middleware::Recover`, I managed to write one, see [this gist](https://gist.github.com/Meralis40/911ff848a427be7fffff748821ed1d27). Do you have any suggestion before I try to make a PR ?

**Comment by mehcode** [comment]
@Meralis40 Good timing. Just finished up the changes I had planned for the middleware (not pushed yet, give me another few minutes). Let me adjust your gist a tad to compile with my recent changes.

```rust
fn recover_panics(next: BoxHandler) -> BoxHandler {
    Box::new(move |ctx: Context| {
        AssertUnwindSafe(futures::lazy(|| -> BoxFutureResponse {
            Box::new(next.call(ctx))
        }))
        .catch_unwind()
        .then(move |result| {
            match result {
                Err(_err) => {
                    // a panic occurs, send back an InternalServerError response
                    futures::future::ok(Response::new().with_status(Status::InternalServerError))
                },
                Ok(Err(e)) => { futures::future::err(e) },
                Ok(Ok(x))  => { futures::future::ok(x) },
            }
        })
    })
}
```

There is a `middleware` module now. Feel free to drop this in there in `middleware/recover` file.
